name: Build CI

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - name: Build Go Binary
        run: go build -o gsc
      - name: Test Go Binary
        run: ./gsc https://github.com/BRAVO68WEB/pacsearch/tree/main/apps/pacsearch-app/components pacsearch_components
      - name: Check for changes
        run: git diff --exit-code